# Generated by Django 4.2.6 on 2023-11-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_comment_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
